### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by ghost** [AbirHasan2005/TelegramScraper#25]
Traceback (most recent call last):
  File "scraper.py", line 85, in <module>
    all_participants = client.get_participants(target_group, aggressive=True)
  File "/run/media/vadiki/D_238_GB_WD/Projects/python/Telegram_chat_user_dumper/env/lib64/python3.8/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/run/media/vadiki/D_238_GB_WD/Projects/python/Telegram_chat_user_dumper/env/lib64/python3.8/site-packages/telethon/client/chats.py", line 507, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "/run/media/vadiki/D_238_GB_WD/Projects/python/Telegram_chat_user_dumper/env/lib64/python3.8/site-packages/telethon/requestiter.py", line 113, in collect
    async for message in self:
  File "/run/media/vadiki/D_238_GB_WD/Projects/python/Telegram_chat_user_dumper/env/lib64/python3.8/site-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/run/media/vadiki/D_238_GB_WD/Projects/python/Telegram_chat_user_dumper/env/lib64/python3.8/site-packages/telethon/client/chats.py", line 222, in _load_next_chunk
    results = await self.client(self.requests)
  File "/run/media/vadiki/D_238_GB_WD/Projects/python/Telegram_chat_user_dumper/env/lib64/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/run/media/vadiki/D_238_GB_WD/Projects/python/Telegram_chat_user_dumper/env/lib64/python3.8/site-packages/telethon/client/users.py", line 80, in _call
    raise MultiError(exceptions, results, requests)
telethon.errors.common.MultiError: ([FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)')], [None, None, <telethon.tl.types.channels.ChannelParticipants object at 0x7f82c18d76d0>, None, <telethon.tl.types.channels.ChannelParticipants object at 0x7f82c18cc2b0>, None, None, <telethon.tl.types.channels.ChannelParticipants object at 0x7f82c18c12e0>, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], [<telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1baca90>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1bacb50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1bacc10>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1baccd0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1bacd90>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1bace50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1bacf10>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1bacfd0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1baf0d0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1baf190>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1baf250>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1baf310>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1baf3d0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1baf490>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1baf550>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1baf610>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1baf6d0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1baf790>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1baf850>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1baf910>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1baf9d0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1bafa90>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1bafb50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1bafc10>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1bafcd0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f82c1bafd90>])
(env) vadiki@localhost:/run/media/vadiki/D_238_GB_WD/Projects/python/Telegram_chat_user_dumper/TeleGram-Scraper>

**Comment by CJ-ONYERO99** [comment]
Traceback (most recent call last):
  File "/storage/emulated/0/TelScrapper/ScrapperUpdate/Scrapper.py", line 88, in <module>
    all_participants = client.get_participants(target_group, aggressive=True)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/data/data/com.termux/files/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/chats.py", line 507, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/requestiter.py", line 113, in collect
    async for message in self:
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/chats.py", line 222, in _load_next_chunk
    results = await self.client(self.requests)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/users.py", line 80, in _call
    raise MultiError(exceptions, results, requests)
telethon.errors.common.MultiError: ([None, None, FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)')], [<telethon.tl.types.channels.ChannelParticipants object at 0x762a5117e0>, <telethon.tl.types.channels.ChannelParticipants object at 0x762a512470>, None, <telethon.tl.types.channels.ChannelParticipants object at 0x762a512260>, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], [<telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a4e80>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a4f40>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a5000>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a50c0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a5180>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a5240>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a5300>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a53c0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a5480>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a5540>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a5600>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a56c0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a5780>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a5840>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a5900>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a59c0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a5a80>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a5b40>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a5c00>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a5cc0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a5d80>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a5e40>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a5f00>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a6080>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x762a4a6140>])
Segmentation fault

**Comment by jakbin** [comment]
remove `aggressive=True` from `scraper.py` because telethon have removed this argument.

**Comment by ghost** [comment]
Thank you and Happy New Year!

пт, 30 дек. 2022 г. в 16:32, Dhruv Jagdish ***@***.***>:
